

#
# User configuration sourced by interactive shells
#

# Change default zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# Alias
alias _='sudo'
alias maj='sudo apt -y update ; sudo apt -y dist-upgrade && sudo apt -y autoremove'
